- name: User
  hosts: all
  handlers:
  - name: Apply files
    shell: cd ~/dotfiles && ./apply.sh
  - name: Test connection
    ping:

  tasks:
  - set_fact:
      repo: 'git@github.com:pdostal/dotfiles.git'
    when: inventory_hostname == 'local'
  - set_fact:
      repo: 'https://github.com/pdostal/dotfiles.git'
    when: inventory_hostname != 'local'

  - name: Fetch repository
    git: repo={{ repo }} dest=~/dotfiles
    when: inventory_hostname != 'local'
    notify: Apply files
  - name: Ensure .profile exists
    file: path=~/.profile state=touch mode=700
  - name: Include .bashrc
    lineinfile: dest=~/.profile regexp=~/.bashrc line=source ~/.bashrc
    notify: Test connection
  - name: Include oh-my-git
    lineinfile: dest=~/.profile regexp=~/dotfiles/oh-my-git/ line=source ~/dotfiles/oh-my-git/prompt.sh
    notify: Test connection
    when: inventory_hostname == 'local'

  - name: Ensure ~/.ssh exists
    file: path=~/.ssh state=directory mode=700
  - name: Paste my key
    lineinfile: dest=~/.ssh/authorized_keys regexp='pavel@laptop.pdostal.cz' line='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCW1AFnflfnPfKg12oAlESachI/BKlMXQ4CpAHBqrVBqlyb4bbma9fNNAlomD+qzKkorxRGIkxK/6WwIwTZpaiz84H+FlpIrPJeiz1jDeSqW+apP/trh95CvwKgCocXZQeA8O0lRy1RtPZYwKNONR427urIYTavrFcxpqeEYD/C2A+v4QdGlSJQHXsMbgZ2egFJlG7n/b0o4tJAH4YmiiKIECq7S03SHWzd8d5ZKzSxwGq35C/HBLBcgvi47jSQZC9H4eyuFY8xSb+fvi4jPXaZlbDlDaJJ9GrwgWbjyJIiwyMAhrxlaG31DmcJoMecxZ0f/ZXIDCSzSG02N93SsBH7 pavel@laptop.pdostal.cz'
    notify: Test connection
