- name: User
  hosts: all
  handlers:
  - name: Test connection
    ping:

  tasks:
  - name: Set repo fact {local}
    when: inventory_hostname == 'local'
    set_fact:
      repo: 'git@github.com:pdostal/dotfiles.git'
  - name: Set repo fact {others}
    when: inventory_hostname != 'local'
    set_fact:
      repo: 'https://github.com/pdostal/dotfiles.git'

  - name: Fetch repository
    git: repo={{ repo }} dest=~/dotfiles accept_hostkey=yes
  - name: Apply files
    shell: cd ~/dotfiles && ./apply.sh
  - name: Ensure .profile exists
    file: path=~/.profile state=touch mode=700
  - name: Include .bashrc
    lineinfile: dest=~/.profile regexp=~/.bashrc line='source ~/.bashrc'
    notify: Test connection
  - name: Include oh-my-git
    lineinfile: dest=~/.profile regexp=~/dotfiles/oh-my-git/ line='source ~/dotfiles/oh-my-git/prompt.sh'
    notify: Test connection
    when: inventory_hostname == 'local'

  - name: Ensure ~/.ssh exists
    file: path=~/.ssh state=directory mode=700
  - name: Paste my key
    lineinfile: dest=~/.ssh/authorized_keys regexp='pavel@laptop.pdostal.cz' line='ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNqDvUZvnRqJ4ZLz/wjiCdqG/iTZBCxo9NjmxEbQR8sNPWnm39dw/10xSz2cC7MmkOOeACEr0ihpZfS48Hm8158= pavel@laptop.pdostal.cz'
    notify: Test connection
