- name: User
  hosts: all
  handlers:
  - name: Test connection
    ping:

  tasks:
  - name: Clone repository
    git: repo=git@github.com:pdostal/dotfiles.git dest=~/dotfiles accept_hostkey=yes
  - name: Apply files
    shell: cd ~/dotfiles && ./apply.sh
  - name: Ensure .profile exists
    file: path=~/.profile state=touch mode=700
  - name: Include .bashrc
    lineinfile: dest=~/.profile regexp=~/.bashrc line='source ~/.bashrc'
    notify: Test connection

  - name: Clone github gitignore
    git: repo=git@github.com:github/gitignore.git dest=~/external/github_gitignore

  - name: Clone oh-my-git
    git: repo=git@github.com:arialdomartini/oh-my-git.git dest=~/external/oh-my-git
  - name: Include oh-my-git
    lineinfile: dest=~/.profile regexp=~/external/oh-my-git/ line='source ~/external/oh-my-git/prompt.sh'
    notify: Test connection
    when: inventory_hostname == 'local'

  - name: Ensure ~/.ssh exists
    file: path=~/.ssh state=directory mode=700
  - name: Paste my key
    lineinfile: dest=~/.ssh/authorized_keys regexp='pavel@laptop.pdostal.cz' line='ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNqDvUZvnRqJ4ZLz/wjiCdqG/iTZBCxo9NjmxEbQR8sNPWnm39dw/10xSz2cC7MmkOOeACEr0ihpZfS48Hm8158= pavel@laptop.pdostal.cz'
    notify: Test connection
