- name: User
  hosts: all
  handlers:
  - name: Test connection
    ping:

  tasks:
  - name: Clone repository
    git: repo=git@github.com:pdostal/dotfiles.git dest=~/dotfiles accept_hostkey=yes
  - name: Apply files
    shell: cd ~/dotfiles && ./apply.sh {{ ansible_user_dir }} {{ ansible_user_dir }}/dotfiles
  - name: Ensure .profile exists
    file: path=~/.profile state=touch mode=700
  - name: Include .bashrc
    lineinfile: >
      dest=~/.profile
      create=yes
      regexp=~/.bashrc
      line='source ~/.bashrc'
    notify: Test connection

  - name: Clone github gitignore
    git: repo=git@github.com:github/gitignore.git dest=~/external/github_gitignore

  - name: Clone oh-my-git
    git: repo=git@github.com:arialdomartini/oh-my-git.git dest=~/external/oh-my-git
  - name: Include oh-my-git
    lineinfile: >
      dest=~/.profile
      create=yes
      regexp=~/external/oh-my-git/
      line='source ~/external/oh-my-git/prompt.sh'
    notify: Test connection
    when: inventory_hostname == 'local'

  - name: Ensure ~/.ssh exists
    file: path=~/.ssh state=directory mode=700
  - name: Paste rsa key
    lineinfile: dest=~/.ssh/authorized_keys regexp='pavel@pdostal.cz' line='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCW1AFnflfnPfKg12oAlESachI/BKlMXQ4CpAHBqrVBqlyb4bbma9fNNAlomD+qzKkorxRGIkxK/6WwIwTZpaiz84H+FlpIrPJeiz1jDeSqW+apP/trh95CvwKgCocXZQeA8O0lRy1RtPZYwKNONR427urIYTavrFcxpqeEYD/C2A+v4QdGlSJQHXsMbgZ2egFJlG7n/b0o4tJAH4YmiiKIECq7S03SHWzd8d5ZKzSxwGq35C/HBLBcgvi47jSQZC9H4eyuFY8xSb+fvi4jPXaZlbDlDaJJ9GrwgWbjyJIiwyMAhrxlaG31DmcJoMecxZ0f/ZXIDCSzSG02N93SsBH7 pdostal@pdostal.cz'
    notify: Test connection
  - name: Paste yubikey
    lineinfile: dest=~/.ssh/authorized_keys regexp='yubikey@pdostal.cz' line='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCxs3F+tCvW9KH7FB4L+9MkP7jMfMrECkjE7+oVGgjPIZfmyg7dYBL5JWQnXuEe2mvYpB1Z1FaeaGji9g9GGKh3W/BOHnxJv+RNTKFSwQfFP6m5c2cLYl8lvRGpqCarZEfwfdNWDw6Goi+uGwKvZx4Zzs5cwoUfB832b23udSIqXuSCRpa9pTBvSSQySYxxQSIrM5phZy6i1AThhNjN1GLXiNmyacAfprZjLg43U7oi/eN6xqQU/sZLEarowTE17F82oU8Yi6eTWAb7J0282r5RP5TESwjb7qePOexCRY9qiwH5rFE/dTRLDTJfvWIpu5nYK85xh2AZuxpPF1x99h5t yubikey@pdostal.cz'
    notify: Test connection

  - name: Disable installing gem documentation
    lineinfile: >
      dest=~/.gemfile
      create=yes
      regexp=--no-document
      line='gem: --no-document'
